### ISSUE TITLE
Provide a ChangeLog 

### ISSUE THREAD

**Issue by asuweb** [Snapchat/KeyDB-docs#54]
Currently there is no changelog that is easily found.

This is essential to understand fundamental changes between versions

**Comment by benschermel** [comment]
Thanks for the request.  This is maintained on the Github project and published as [Release Notes](https://github.com/Snapchat/KeyDB/releases). To help make them easier to find, I have added a link to the KeyDB release notes on the website in the sidebar under ‘More→KeyDB Release Notes (Changelog)’. A changelog is also shipped with all Debian packages.

**Comment by abdullahra634-dotcom** [comment]
> Currently there is no changelog that is easily found.
> 
> 
> 
> This is essential to understand fundamental changes between versions
