### ISSUE TITLE
Documentation: support for TLS

### ISSUE THREAD

**Issue by DreadfulCode** [Snapchat/KeyDB-docs#57]
There appears to be a discrepency on TLS support. Is TLS a feature available by default or does this require building from source? 

Is TLS in the builds pulled from .git or the PPA's?

On https://github.com/Snapchat/KeyDB/blob/main/TLS.md  it says:

TLS support is enabled in the default build. To build without TLS, run make **BUILD_TLS=no.**

But on 
https://docs.keydb.dev/docs/encryption/ it says:

To build with TLS support you'll need OpenSSL development libraries (e.g. libssl-dev on Debian/Ubuntu).

Run **make BUILD_TLS=yes**.

**Comment by benschermel** [comment]
Thanks for catching this, yes it is built by default with TLS. I have updated on our github[ README](https://github.com/Snapchat/KeyDB#building-keydb) as well as the link you provided in docs.
